var GALLERY_IMAGES = [
  {id:"5TAsh3h",src:"https://i.imgur.com/5TAsh3hl.jpg",fullSrc:"https://i.imgur.com/5TAsh3h",category:"ai-art",label:"AI Art"},
  {id:"i1OAsJR",src:"https://i.imgur.com/i1OAsJRl.jpg",fullSrc:"https://i.imgur.com/i1OAsJR",category:"ai-art",label:"AI Art"},
  {id:"UGitYNB",src:"https://i.imgur.com/UGitYNBl.jpg",fullSrc:"https://i.imgur.com/UGitYNB",category:"ai-art",label:"AI Art"},
  {id:"cSFsKra",src:"https://i.imgur.com/cSFsKral.jpg",fullSrc:"https://i.imgur.com/cSFsKra",category:"ai-art",label:"AI Art"},
  {id:"QWc56oj",src:"https://i.imgur.com/QWc56ojl.jpg",fullSrc:"https://i.imgur.com/QWc56oj",category:"ai-art",label:"AI Art"},
  {id:"6YHQRMW",src:"https://i.imgur.com/6YHQRMWl.jpg",fullSrc:"https://i.imgur.com/6YHQRMW",category:"ai-art",label:"AI Art"},
  {id:"W2yMA4j",src:"https://i.imgur.com/W2yMA4jl.jpg",fullSrc:"https://i.imgur.com/W2yMA4j",category:"ai-art",label:"AI Art"},
  {id:"W2UN2wd",src:"https://i.imgur.com/W2UN2wdl.jpg",fullSrc:"https://i.imgur.com/W2UN2wd",category:"ai-art",label:"AI Art"},
  {id:"AUPoxrg",src:"https://i.imgur.com/AUPoxrgl.jpg",fullSrc:"https://i.imgur.com/AUPoxrg",category:"ai-art",label:"AI Art"},
  {id:"p0P2o1x",src:"https://i.imgur.com/p0P2o1xl.jpg",fullSrc:"https://i.imgur.com/p0P2o1x",category:"ai-art",label:"AI Art"},
  {id:"c9KSEMx",src:"https://i.imgur.com/c9KSEMxl.jpg",fullSrc:"https://i.imgur.com/c9KSEMx",category:"ai-art",label:"AI Art"},
  {id:"CjN79EX",src:"https://i.imgur.com/CjN79EXl.jpg",fullSrc:"https://i.imgur.com/CjN79EX",category:"ai-art",label:"AI Art"},
  {id:"RuLrd6T",src:"https://i.imgur.com/RuLrd6Tl.jpg",fullSrc:"https://i.imgur.com/RuLrd6T",category:"ai-art",label:"AI Art"},
  {id:"givKksu",src:"https://i.imgur.com/givKksul.jpg",fullSrc:"https://i.imgur.com/givKksu",category:"ai-art",label:"AI Art"},

  {id:"1tM9t54",src:"https://i.imgur.com/1tM9t54l.jpg",fullSrc:"https://i.imgur.com/1tM9t54",category:"artwork",label:"Artwork"},
  {id:"POQfzFw",src:"https://i.imgur.com/POQfzFwl.jpg",fullSrc:"https://i.imgur.com/POQfzFw",category:"artwork",label:"Artwork"},
  {id:"vaPODU3",src:"https://i.imgur.com/vaPODU3l.jpg",fullSrc:"https://i.imgur.com/vaPODU3",category:"artwork",label:"Artwork"},
  {id:"JfMJj0t",src:"https://i.imgur.com/JfMJj0tl.jpg",fullSrc:"https://i.imgur.com/JfMJj0t",category:"artwork",label:"Artwork"},
  {id:"4Trc8Xn",src:"https://i.imgur.com/4Trc8Xnl.jpg",fullSrc:"https://i.imgur.com/4Trc8Xn",category:"artwork",label:"Artwork"},
  {id:"KFtJ574",src:"https://i.imgur.com/KFtJ574l.jpg",fullSrc:"https://i.imgur.com/KFtJ574",category:"artwork",label:"Artwork"},
  {id:"umPAVXT",src:"https://i.imgur.com/umPAVXTl.jpg",fullSrc:"https://i.imgur.com/umPAVXT",category:"artwork",label:"Artwork"},
  {id:"me4jqa5",src:"https://i.imgur.com/me4jqa5l.jpg",fullSrc:"https://i.imgur.com/me4jqa5",category:"artwork",label:"Artwork"},
  {id:"KWu4zap",src:"https://i.imgur.com/KWu4zapl.jpg",fullSrc:"https://i.imgur.com/KWu4zap",category:"artwork",label:"Artwork"},
  {id:"p42tvvp",src:"https://i.imgur.com/p42tvvpl.jpg",fullSrc:"https://i.imgur.com/p42tvvp",category:"artwork",label:"Artwork"},
  {id:"HMLwQye",src:"https://i.imgur.com/HMLwQyel.jpg",fullSrc:"https://i.imgur.com/HMLwQye",category:"artwork",label:"Artwork"},
  {id:"eqSdhe6",src:"https://i.imgur.com/eqSdhe6l.jpg",fullSrc:"https://i.imgur.com/eqSdhe6",category:"artwork",label:"Artwork"},
  {id:"go12zWN",src:"https://i.imgur.com/go12zWNl.jpg",fullSrc:"https://i.imgur.com/go12zWN",category:"artwork",label:"Artwork"},
  {id:"IgysOkY",src:"https://i.imgur.com/IgysOkYl.jpg",fullSrc:"https://i.imgur.com/IgysOkY",category:"artwork",label:"Artwork"},

  {id:"ba6XOpp",src:"https://i.imgur.com/ba6XOppl.jpg",fullSrc:"https://i.imgur.com/ba6XOpp",category:"jb-sketches",label:"Jeremy Burke Sketches"},
  {id:"VrnG1VU",src:"https://i.imgur.com/VrnG1VUl.jpg",fullSrc:"https://i.imgur.com/VrnG1VU",category:"jb-sketches",label:"Jeremy Burke Sketches"},
  {id:"2Zq2sZO",src:"https://i.imgur.com/2Zq2sZOl.jpg",fullSrc:"https://i.imgur.com/2Zq2sZO",category:"jb-sketches",label:"Jeremy Burke Sketches"},
  {id:"lYt7YvA",src:"https://i.imgur.com/lYt7YvAl.jpg",fullSrc:"https://i.imgur.com/lYt7YvA",category:"jb-sketches",label:"Jeremy Burke Sketches"},
  {id:"tcXRnPU",src:"https://i.imgur.com/tcXRnPUl.jpg",fullSrc:"https://i.imgur.com/tcXRnPU",category:"jb-sketches",label:"Jeremy Burke Sketches"},
  {id:"U6cP3qL",src:"https://i.imgur.com/U6cP3qLl.jpg",fullSrc:"https://i.imgur.com/U6cP3qL",category:"jb-sketches",label:"Jeremy Burke Sketches"},
  {id:"aa5ESSJ",src:"https://i.imgur.com/aa5ESSJl.jpg",fullSrc:"https://i.imgur.com/aa5ESSJ",category:"jb-sketches",label:"Jeremy Burke Sketches"},
  {id:"j5TsvXL",src:"https://i.imgur.com/j5TsvXLl.jpg",fullSrc:"https://i.imgur.com/j5TsvXL",category:"jb-sketches",label:"Jeremy Burke Sketches"},

  {id:"1jRFIri",src:"https://i.imgur.com/1jRFIril.jpg",fullSrc:"https://i.imgur.com/1jRFIri",category:"my-creations",label:"My Creations"},
  {id:"h8KaxVA",src:"https://i.imgur.com/h8KaxVAl.jpg",fullSrc:"https://i.imgur.com/h8KaxVA",category:"my-creations",label:"My Creations"},
  {id:"5xXUW4u",src:"https://i.imgur.com/5xXUW4ul.jpg",fullSrc:"https://i.imgur.com/5xXUW4u",category:"my-creations",label:"My Creations"},
  {id:"6RaURHz",src:"https://i.imgur.com/6RaURHzl.jpg",fullSrc:"https://i.imgur.com/6RaURHz",category:"my-creations",label:"My Creations"},
  {id:"aqTB5jN",src:"https://i.imgur.com/aqTB5jNl.jpg",fullSrc:"https://i.imgur.com/aqTB5jN",category:"my-creations",label:"My Creations"},
  {id:"jOc6RIH",src:"https://i.imgur.com/jOc6RIHl.jpg",fullSrc:"https://i.imgur.com/jOc6RIH",category:"my-creations",label:"My Creations"},
  {id:"qX6oLku",src:"https://i.imgur.com/qX6oLkul.jpg",fullSrc:"https://i.imgur.com/qX6oLku",category:"my-creations",label:"My Creations"},
   {id:"8IG2EKw",src:"https://i.imgur.com/8IG2EKwl.jpg",fullSrc:"https://i.imgur.com/8IG2EKw",category:"my-creations",label:"My Creations"},
  {id:"vREvUcV",src:"https://i.imgur.com/vREvUcVl.jpg",fullSrc:"https://i.imgur.com/vREvUcV",category:"my-creations",label:"My Creations"},
  {id:"KgQCHk9",src:"https://i.imgur.com/KgQCHk9l.jpg",fullSrc:"https://i.imgur.com/KgQCHk9",category:"my-creations",label:"My Creations"},
  {id:"8ZHouOg",src:"https://i.imgur.com/8ZHouOgl.jpg",fullSrc:"https://i.imgur.com/8ZHouOg",category:"my-creations",label:"My Creations"},
  {id:"NPtaXiW",src:"https://i.imgur.com/NPtaXiWl.jpg",fullSrc:"https://i.imgur.com/NPtaXiW",category:"my-creations",label:"My Creations"},
  {id:"65HGmVs",src:"https://i.imgur.com/65HGmVsl.jpg",fullSrc:"https://i.imgur.com/65HGmVs",category:"my-creations",label:"My Creations"},
  {id:"n5e5StJ",src:"https://i.imgur.com/n5e5StJl.jpg",fullSrc:"https://i.imgur.com/n5e5StJ",category:"my-creations",label:"My Creations"},

  {id:"YH7kg3D",src:"https://i.imgur.com/YH7kg3Dl.jpg",fullSrc:"https://i.imgur.com/YH7kg3D",category:"photography",label:"Photography"},
  {id:"PxJwK2o",src:"https://i.imgur.com/PxJwK2ol.jpg",fullSrc:"https://i.imgur.com/PxJwK2o",category:"photography",label:"Photography"},
  {id:"jHTEUWi",src:"https://i.imgur.com/jHTEUWil.jpg",fullSrc:"https://i.imgur.com/jHTEUWi",category:"photography",label:"Photography"},
  {id:"cgWVMbC",src:"https://i.imgur.com/cgWVMbCl.jpg",fullSrc:"https://i.imgur.com/cgWVMbC",category:"photography",label:"Photography"},
  {id:"ojk2SyG",src:"https://i.imgur.com/ojk2SyGl.jpg",fullSrc:"https://i.imgur.com/ojk2SyG",category:"photography",label:"Photography"},
  {id:"uOXmt7v",src:"https://i.imgur.com/uOXmt7vl.jpg",fullSrc:"https://i.imgur.com/uOXmt7v",category:"photography",label:"Photography"},
  {id:"lNlAf7b",src:"https://i.imgur.com/lNlAf7bl.jpg",fullSrc:"https://i.imgur.com/lNlAf7b",category:"photography",label:"Photography"},
  {id:"IQEELEr",src:"https://i.imgur.com/IQEELErl.jpg",fullSrc:"https://i.imgur.com/IQEELEr",category:"photography",label:"Photography"},
  {id:"Wrunjvd",src:"https://i.imgur.com/Wrunjvdl.jpg",fullSrc:"https://i.imgur.com/Wrunjvd",category:"photography",label:"Photography"},
  {id:"wFGSax5",src:"https://i.imgur.com/wFGSax5l.jpg",fullSrc:"https://i.imgur.com/wFGSax5",category:"photography",label:"Photography"},
  {id:"8iyzhSi",src:"https://i.imgur.com/8iyzhSil.jpg",fullSrc:"https://i.imgur.com/8iyzhSi",category:"photography",label:"Photography"},
  {id:"xhfPXVA",src:"https://i.imgur.com/xhfPXVAl.jpg",fullSrc:"https://i.imgur.com/xhfPXVA",category:"photography",label:"Photography"},
  {id:"qh27WJ6",src:"https://i.imgur.com/qh27WJ6l.jpg",fullSrc:"https://i.imgur.com/qh27WJ6",category:"photography",label:"Photography"},
  {id:"NWfjDkG",src:"https://i.imgur.com/NWfjDkGl.jpg",fullSrc:"https://i.imgur.com/NWfjDkG",category:"photography",label:"Photography"},

];

